---
controller:
    host: 10.0.0.11
    hostname: "controller"
network:
    host: 10.0.0.21
    hostname: "network"
compute:
    host: 10.0.0.31
    hostname: "compute1"
#ansible_host_ip: 10.0.0.11
#ansible_host_name: node1
ntp_servers: [ "{{ controller.hostname }}" ]
mysql:
   root_password: '123456'
   bind_address: "{{ controller.host }}"
   bind_name: "{{ controller.host }}"
   port: 3306
   keystone_user: "keystone"
   keystone_password: "keystone_pass"
   glance_user: "glance"
   glance_password: "glance_pass"
   nova_user: "nova"
   nova_password: "nova_pass"
   neutron_user: "neutron"
   neutron_password:  "neutron_pass"
rabbitmq:
   server_ip: 127.0.0.1
   port: 5672
   openstack_user: "openstack"
   openstack_password: "openstack"
keystone:
   mysql_ip: "{{ ansible_host_name }}"
   auth_ip: "{{ ansible_host_name }}"
   service_ip: 127.0.0.1
   admin_password: "admin_pass"
   mysql_port: "{{ mysql.port }}"
   conf_auth_file: /root/.novarc
   keystone_user: "keystone"
   keystone_password: "keystone_pass"
   glance_user: "glance"
   glance_password: "glance_pass"
   nova_user: "nova"
   nova_password: "nova_pass"
   neutron_user: "neutron"
   neutron_password:  "neutron_pass"
   cinder_user: "cinder"
   cinder_password:  "cinder_pass"
METADATA_SECRET: "metadata_secret"
nova_metadata_ip: "{{ ansible_host_name }}"
nova_metadata_listen_port: "8775"


babel_mysql_root_password: 'CHANGEME'

babel_mysql_keystone_user: keystone
babel_mysql_glance_user: glance
babel_mysql_nova_user: nova
babel_mysql_cinder_user: cinder
babel_mysql_neutron_user: neutron
babel_mysql_umbrella_user: umbrella
babel_mysql_nbs_user: nbs

babel_keystone_admin_token: "keystone_pass"
babel_keystone_admin_user: "admin"
babel_glance_admin_user: "{{ babel_mysql_glance_user }}"
babel_nova_admin_user: "{{ babel_mysql_nova_user }}"
babel_neutron_admin_user: "{{ babel_mysql_neutron_user }}"
babel_cinder_admin_user: "{{ babel_mysql_cinder_user }}"

babel_keystone_service_ip: "127.0.0.1"
babel_glance_service_ip: "127.0.0.1"
babel_nova_service_ip: "127.0.0.1"
babel_neutron_service_ip: "127.0.0.1"
babel_cinder_service_ip: "127.0.0.1"
babel_mysql_service_ip: "127.0.0.1"
babel_memcached_service_ip: "127.0.0.1"
babel_rabbitmq_service_ip: "127.0.0.1"

babel_auth_file: /root/.novarc

babel_nfs_server: "10.10.82.121"

babel_public_network_name: "public_admin"
babel_public_network_cidr: "10.10.245.0/24"
babel_public_network_gateway_ip: "10.10.245.253"
babel_public_service_cidr: "192.168.2.0/24"
babel_private_network_cidr: "192.168.138.0/24"
babel_private_tunnel_cidr: "192.168.1.0/24"
babel_vpn_client_ip_pool: "192.168.114.0/23"
babel_vpn_domain_suffix: ".test.vpn.cloud.netease.com"

aggregates_list:
  - {'az': 'az1', 'name': 'az1', 'hosts_name': ['shary001']}
  - {'az': 'az2', 'name': 'az2', 'hosts_name': ['shary002']}


config_mysql:
  bind_host: "127.0.0.1"
  bind_port: 3306

config_memcached:
  bind_host: "127.0.0.1"
  bind_port: 11211

config_rabbitmq:
  bind_host: "127.0.0.1"
  bind_port: 5672
  rabbitmq_user: guest

config_keystone:
  admin_token: "{{ babel_keystone_admin_token }}"
  bind_host: "127.0.0.1"
  public_port: 5000
  admin_port: 35357
  internal_port: 5000
  log_file: keystone.log
  log_dir: /data/log/keystone/
  public_ip: "{{ babel_keystone_service_ip }}"
  admin_ip: "{{ babel_keystone_service_ip }}"
  internal_ip: "{{ babel_keystone_service_ip }}"
  region_name: RegionOne

config_glance:
  bind_api_host: "{{ babel_glance_service_ip }}"
  bind_registry_host: "{{ babel_glance_service_ip }}"
  bind_api_port: 9292
  bind_registry_port: 9191
  log_file: "glance.log"
  log_dir: "/data/log/glance/"
  data_dir: "/data/glance/"
  nfs_image_path: "/home/share/images"
  images:
    - name: "debian-7.2-amd64"
      image_file: debian-7.2.0-amd64-nbs.qcow2
      container_format: bare
      disk_format: qcow2
      os_type: linux
    - name: "ubuntu-12.04.4-server-amd64"
      image_file: ubuntu-12.04.4-server-amd64.qcow2
      container_format: bare
      disk_format: qcow2
      os_type: linux
