---

neutron_mysql_password: "{{ mysql.neutron_password }}"
neutron_keystone_password: "{{ keystone.neutron_password|default('neutron_pass') }}"
neutron_apt_packages:
  - neutron-server 
  - neutron-plugin-ml2 
  - python-neutronclient

neutron_network_packages:
  - neutron-plugin-ml2
  - neutron-plugin-openvswitch-agent 
  - neutron-l3-agent 
  - neutron-dhcp-agent 
  - neutron-metadata-agent
neutron_compute_packages:
  - neutron-plugin-ml2 
  - neutron-plugin-openvswitch-agent

external_bridge_ifname: "{{ neutron_external_bridge_ifname }}"
instance_tunnels_ifip_address: 10.0.1.21
neutron_mysql_pass: "{{ mysql.neutron_password }}"
