---

- name: Create nova databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql.root_password }}"
    name: "{{ item }}"
    state: present
  with_items:
    - nova

- name: Crete database user
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql.root_password }}"
    name: "nova"
    password: "{{ nova_mysql_pass }}"
    priv: "nova.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '%'
