---

- name: Remove package rabbit if found for upgrade
  file:
    path: "{{ rabbitmq_package_path }}"
    state: absent
  tags:
    - rabbitmq-upgrade
    - rabbitmq-package-deb
    - rabbitmq-package-deb-get

- name: Download the RabbitMQ package
  get_url:
    url: "{{ rabbitmq_package_url }}"
    dest: "{{ rabbitmq_package_path }}"
    mode: "0644"
    sha256sum: "{{ rabbitmq_package_sha256 }}"
  register: package_download
  until: package_download|success
  tags:
    - rabbitmq-package-deb
    - rabbitmq-package-deb-get

- name: Create the local directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    group: "{{ item.owner|default('root') }}"
    owner: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0755') }}"
    recurse: "{{ item.recurse|default('false') }}"
  with_items:
    - { path: "/etc/rabbitmq/" }
  tags:
    - rabbitmq-config

- name: Create rabbitmq config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "rabbitmq.config.j2", dest: "/etc/rabbitmq/rabbitmq.conf" }
    - { src: "rabbitmq-server.j2", dest: "/etc/default/rabbitmq-server" }

