---
- name: generate the configuration of rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
    backup=yes
  notify: restart rabbitmq-server
