---
- name: Create rabbitmq config
  register: rabbit_config_changed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "rabbitmq.config.j2", dest: "/etc/rabbitmq/rabbitmq.config" }
    - { src: "rabbitmq-server.j2", dest: "/etc/default/rabbitmq-server" }

- include: rabbitmq_restart.yml
  when: rabbit_config_changed|changed

- name: Ensure default rabbitmq guest user is removed
  rabbitmq_user:
    user: guest
    state: absent
  tags:
    - rabbitmq-user
