---
- name: Install mysql packages
  apt: 
    pkg: "{{ item }}"
  with_items: mysql_packages

- name: Ensure mysql is stopped
  service:
    name: mysql
    state: stopped

- name: create mysqld_openstack.cnf
  template:
    src: mysqld_openstack.cnf.j2
    dest: /etc/mysql/conf.d/mysqld_openstack.cnf
    mode: 0755

- name: update the my.cnf
  template:
    src: mysql_my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644

- name: ensure mysql is started and running
  service:
    name: mysql
    state: restarted
    pattern: mysqld
    enabled: yes

- name: update mysql root password for all accounts
  mysql_user:
    login_user: root
    login_password: "{{ mysql_default_root_password }}"
    name: root
    host: "localhost"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  ignore_errors: true

- name: copy .my.cnf file with root password credentials
  template:
    src: "root_dot_my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: reconfigure the root account for remote use
  mysql_user:
#   login_user: root
#   login_password: "{{ mysql_default_root_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"
    - "%"

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"
    - "%" 
