---
- name: Create databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item }}"
    state: present
  with_items:
    - keystone

- name: Create database users
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: "keystone"
    password: "{{ keystone_mysql_pass }}"
    priv: "keystone.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '%'

- name: Sync keystone db
  command: keystone-manage db_sync
  sudo: yes
  tags: keystone-config
