---
- name: Configure image api
  lineinfile:
     dest: "{{ item }}"
     regexp: "^export OS_IMAGE_API_VERSION"
     line: "export OS_IMAGE_API_VERSION=2"
     state: present
  with_items: keystone.conf_auth_file

- name: Create image directory
  file:
     path: "{{ item }}"
     state: directory
     owner: root
     group: root
     mode: 0755
  with_items: glance_images_path

- name: Download an image
# shell: "{{ item }}"
# with_items:
#   - wget -P "{{glance_images_path}}" http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
  get_url:
    url:  http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    dest: "{{glance_images_path}}"

# name: Create an image
# shell: "{{ item }}"
# with_items:
#   - glance image-create --name "cirros-0.3.4-x86_64" --file {{ glance_images_path }}/cirros-0.3.4-x86_64-disk.img --disk-format qcow2 --container-format bare --visibility public
# shell: |
#     source {{ keystone.conf_auth_file }}
#     glance image-create  --name cirros-0.3.4-x86_64 --file {{ glance_images_path }}/cirros-0.3.4-x86_64-disk.img --disk-format qcow2 --container-format bare --visibility public 
# args:
#   executable: /bin/bash

- name: List images
# shell: "{{ item }}"
# with_items:
  shell: |
      source {{ keystone.conf_auth_file }}
      glance image-list
  args:
    executable: /bin/bash
  register: glance_result
  failed_when: glance_result.rc != 0
