---
- name: Install ntp server
  apt: name={{ item }}
  with_items:
    - ntp
    - ntpdate
  
- name: copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: Ensure ntp restart
  service: name=ntp state=restarted enabled=yes

- name: sync time
  command: ntpq -p

