---

nova_compute_packages:
  - nova-compute 
  - sysfsutils

nova_service_names:
  - nova-api
  - nova-cert
  - nova-consoleauth
  - nova-scheduler
  - nova-conductor
  - nova-novncproxy

nova_compute_names:
  - nova-compute
  - sysfsutils

nova_mysql_pass: "{{mysql.nova_password}}"
nova_mysql_ip: "{{mysql.bind_name}}"
my_ip: "{{ Controller.host }}"
## dynamic change ip
compute_manage_if_ip: "{{ Compute.host }}"
vnc_ip: "{{ Controller.hostname }}"
nova_keystone_password: "{{ keystone.nova_password }}"
mysql_address: "{{ nova_mysql_ip }}"
glance_host: "{{ nova_mysql_ip}}"
