---

- name: Remove 127.0.1.1 row
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    state: absent

- name: Add hostname
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }}  {{ item.name }} "
    regexp: "^{{ item.ip }}"
    state: present
  with_items:
    # { ip: "{{deploy_host_ip}}", name: "{{deploy_host_name}}" }
    # { ip: "{{ ansible_host_ip }}", name: "{{ ansible_host_name }}" }
    - { ip: "{{ controller.host }}", name: "{{ controller.hostname }}" }
    - { ip: "{{ network.host }}", name: "{{ network.hostname }}" }
    - { ip: "{{ compute.host }}", name: "{{ compute.hostname }}" }
