---

- name: Ensure the memcache user exists
  user:
    name: "{{ memcached_user }}"
    comment: "memcached user"
    system: "yes"
    shell: "/bin/false"
    createhome: "no"

- name: Ensure memcached directories
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
  with_items:
    - "{{ memcached_log | dirname }}"
