---

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  register: install_packges
  until: install_packages|success
  with_items: memcached_apt_packages
