---

- hosts: all
  roles:
#   - kilo_host_config
#   - ntp_servers 
    # ntp_servers: [ deployhost ]

- hosts: all
  roles:
#   - kilo_rabbitmq
#   - kilo_mysql
#   - kilo_keystone
#   - kilo_glance

- hosts: compute
  roles:
#   - kilo_nova
#   - kilo_neutron
    - kilo_dashboard
