---

- hosts: all
  roles:
    - kilo_host_config
    - ntp_servers 

# hosts: controller
# roles:
#   - kilo_rabbitmq
#   - kilo_mysql
#   - kilo_keystone
#   - kilo_glance

# hosts: compute
# roles:
#   - kilo_nova
#   - kilo_neutron
#   - kilo_dashboard
