---

- hosts: all
  roles:
    - role: prepare

    - role: ntp_servers 
      ntp_servers: [ deployhost ]

- hosts: all
  roles:
    - mysql
    - rabbitmq
    - keystone_server
    
#   - babel_mysql
#   - babel_keystone
