---

glance_apt_packages:
  - glance
  - python-glanceclient

glance_mysql_pass: "{{ mysql.glance_password }}"
glance_mysql_address: "{{ mysql.bind_name|default('127.0.0.1') }}"
glance_default_store: file
glance_filesystem_store_datadir: /var/lib/glance/images/
glance_api_bind_address: "0.0.0.0"
glance_api_bind_port: 9292
glance_registry_host: "127.0.0.1"
glance_registry_port: 9191
glance_api_service_proto: http
glance_rabbit_user: " {{ rabbitmq.openstack_user|default('openstack') }}"
glance_rabbit_password: "{{rabbitmq.openstack_password|default('openstack') }}"
glance_keystone_ip: "127.0.0.1"
glance_keystone_pass: "{{ keystone.glance_password }}"
glance_images_path: "/var/lib/glance/images/tmp/images"
